import ASGA

/-! `#print axioms` for every result cited in the paper. -/

#print axioms ASGA.envelope_le_iff
#print axioms ASGA.envelope_convexOn
#print axioms ASGA.envelope_antitoneOn
#print axioms ASGA.envelope_nonneg
#print axioms ASGA.envelope_le_one_sub
#print axioms ASGA.envelope_one
#print axioms ASGA.integral_sub_le_hockeyStick
#print axioms ASGA.integral_sub_le_of_hockeyStick_le
#print axioms ASGA.envelope_le_one_sub_integral
#print axioms ASGA.envelope_le_tradeoff
#print axioms ASGA.hockeyStick_swap
#print axioms ASGA.hockeyStick_swap_le
#print axioms ASGA.envR_nonneg
#print axioms ASGA.envS_nonneg
#print axioms ASGA.sum_envR
#print axioms ASGA.sum_envS
#print axioms ASGA.envR_eq_slope_mul_envS
#print axioms ASGA.envPair_tradeoff
#print axioms ASGA.envPair_dominates
#print axioms ASGA.envelope_pair_exists
#print axioms ASGA.envPair_spec

#print axioms ASGA.hockeyStick_le_hockeyStick_add
#print axioms ASGA.hockeyStick_le_hockeyStick_add_tv
#print axioms ASGA.hockeyStick_log_le_hockeyStick_add_tv
#print axioms ASGA.hockeyStick_comp_le
#print axioms ASGA.hockeyStick_map_le
#print axioms ASGA.tvDist_map_le
#print axioms ASGA.tvDist_comp_le
#print axioms ASGA.tvDist_sum_smul_le
#print axioms ASGA.hockeyStick_sum_smul_le
#print axioms ASGA.hockeyStick_comp_le_integral
#print axioms ASGA.tvDist_comp_le_integral
#print axioms ASGA.tvDist_comp_le_tvDist_add
#print axioms ASGA.tvDist_compProd_le
#print axioms ASGA.tvDist_partialTraj_comp_le
#print axioms ASGA.tvDist_partialTraj_comp_le_sum
#print axioms ASGA.tvDist_partialTraj_comp_le_card
#print axioms ASGA.tvDist_withDensity_eq
#print axioms ASGA.cloneDefect_nonneg
#print axioms ASGA.integral_max_sub_eq
#print axioms ASGA.cloneResidual_nonneg
#print axioms ASGA.measurable_cloneResidual
#print axioms ASGA.integrable_cloneResidual
#print axioms ASGA.integral_cloneResidual
#print axioms ASGA.isProbDensity_cloneResidual
#print axioms ASGA.cloneDensity_nonneg
#print axioms ASGA.integral_cloneDensity
#print axioms ASGA.isProbDensity_cloneDensity
#print axioms ASGA.tvDist_withDensity_cloneDensity
#print axioms ASGA.withDensity_cloneDensity
#print axioms ASGA.hockeyStick_eq_integral_rnDeriv
#print axioms ASGA.hockeyStick_swap_eq_integral_rnDeriv
#print axioms ASGA.hockeyStick_log_eq_integral_rnDeriv
#print axioms ASGA.hockeyStick_swap_log_eq_integral_rnDeriv

#print axioms ASGA.Gaussian.setIntegral_exp_tilt
#print axioms ASGA.Gaussian.setIntegral_exp_tilt_Ioi
#print axioms ASGA.Gaussian.setIntegral_exp_tilt_Iio
#print axioms ASGA.Gaussian.hockeyStick_gaussianReal
#print axioms ASGA.Gaussian.hockeyStick_gaussianReal_symm
#print axioms ASGA.Gaussian.integral_lr_sub_pos
#print axioms ASGA.Gaussian.integral_one_sub_mul_lr_pos
#print axioms ASGA.Gaussian.integral_clone_eq_cloneCost
#print axioms ASGA.Gaussian.integral_clone_le_cloneCost
#print axioms ASGA.Gaussian.pi_gaussianReal_eq_withDensity
#print axioms ASGA.Gaussian.integral_clone_euclidean_le_cloneCost
#print axioms ASGA.Gaussian.integral_lr_sub_truncLR
#print axioms ASGA.Gaussian.truncLR_le
#print axioms ASGA.Gaussian.isLRSequence_infinitePi
#print axioms ASGA.Gaussian.callF_succ
#print axioms ASGA.Gaussian.putJ_succ
#print axioms ASGA.Gaussian.callF_zero
#print axioms ASGA.Gaussian.putJ_zero
#print axioms ASGA.Gaussian.convexOn_callF
#print axioms ASGA.Gaussian.convexOn_putJ
#print axioms ASGA.Gaussian.integral_avg_sub_pos
#print axioms ASGA.Gaussian.integral_one_sub_avg_pos
#print axioms ASGA.Gaussian.integral_avg_sub_pos_le
#print axioms ASGA.Gaussian.integral_one_sub_avg_pos_le
#print axioms ASGA.Gaussian.integral_mixture
#print axioms ASGA.Gaussian.integral_avgK_sub_pos
#print axioms ASGA.Gaussian.integral_one_sub_avgK_pos
#print axioms ASGA.Gaussian.sum_prob_eq_one
#print axioms ASGA.Gaussian.counts_bound_forward
#print axioms ASGA.Gaussian.counts_bound_reverse

#print axioms ASGA.Reflection.forward_step
#print axioms ASGA.Reflection.reverse_step
#print axioms ASGA.Reflection.s_neg_of_r_pos
#print axioms ASGA.Reflection.hockeyStick_withDensity
#print axioms ASGA.Reflection.isProbabilityMeasure_chuaReal
#print axioms ASGA.Reflection.isProbabilityMeasure_chuaNull
#print axioms ASGA.Reflection.isProbabilityMeasure_adaptReal
#print axioms ASGA.Reflection.volume_switchSet_ne_zero
#print axioms ASGA.Reflection.hockeyStick_chua_lt_adapt
#print axioms ASGA.Reflection.hockeyStick_chua_lt_adapt_reverse
#print axioms ASGA.Reflection.chua_pair_strictly_improvable

#print axioms ASGA.spreadLow_nonneg
#print axioms ASGA.spreadHigh_nonneg
#print axioms ASGA.spreadLow_add_spreadHigh
#print axioms ASGA.spread_first_moment
#print axioms ASGA.spread_masses
#print axioms ASGA.le_chord_of_convexOn
#print axioms ASGA.integrable_of_convexOn_Icc
#print axioms ASGA.integral_le_spread
#print axioms ASGA.spread_moment_bounds
#print axioms ASGA.poisson_spread
#print axioms ASGA.poisson_spread_convex_order
#print axioms ASGA.callFin_succ
#print axioms ASGA.putFin_succ
#print axioms ASGA.callFin_eq_expectation
#print axioms ASGA.putFin_eq_expectation
#print axioms ASGA.callFin_convexOn
#print axioms ASGA.putFin_convexOn
#print axioms ASGA.callFin_nonneg
#print axioms ASGA.putFin_nonneg
#print axioms ASGA.callFin_antitone
#print axioms ASGA.putFin_monotone
#print axioms ASGA.callFin_of_nonpos
#print axioms ASGA.putFin_of_nonpos
#print axioms ASGA.callFin_eq_zero
#print axioms ASGA.grid_mono
#print axioms ASGA.nodeIndex_spec
#print axioms ASGA.le_interp
#print axioms ASGA.callFin_le_forwardCont
#print axioms ASGA.putFin_le_reverseCont
#print axioms ASGA.callFin_le_nodes
#print axioms ASGA.putFin_le_nodes
#print axioms ASGA.callFin_le_eval
#print axioms ASGA.putFin_le_eval
#print axioms ASGA.expect_le_relocate_top
#print axioms ASGA.expect_le_relocate_bot
#print axioms ASGA.relocate_deficit_nonneg
#print axioms ASGA.relocate_normalized
#print axioms ASGA.expect_le_relocate_atom_top
#print axioms ASGA.expect_le_relocate_atom_bot
#print axioms ASGA.callFin_le_of_dominates
#print axioms ASGA.putFin_le_of_dominates
#print axioms ASGA.callFin_le_relocate_top
#print axioms ASGA.putFin_le_relocate_bot
#print axioms ASGA.callLaw_nonneg
#print axioms ASGA.putLaw_nonneg
#print axioms ASGA.callLaw_eq_integral_pi
#print axioms ASGA.putLaw_eq_integral_pi
#print axioms ASGA.integral_le_spread_sum
#print axioms ASGA.callLaw_le_callFin
#print axioms ASGA.putLaw_le_putFin
#print axioms ASGA.callLaw_le_nodes
#print axioms ASGA.putLaw_le_nodes
#print axioms ASGA.call_posPart_le
#print axioms ASGA.put_posPart_le
#print axioms ASGA.call_tail_correction
#print axioms ASGA.put_tail_correction
#print axioms ASGA.call_tail_correction_tau
#print axioms ASGA.call_tail_correction_tau_div
#print axioms ASGA.callLaw_le_map_add
#print axioms ASGA.putLaw_le_map
#print axioms ASGA.certificate_call_sound
#print axioms ASGA.certificate_put_sound
#print axioms ASGA.finMeasure_eq_discreteMeasure
#print axioms ASGA.discreteMeasure_toReal
#print axioms ASGA.hockeyStick_discreteMeasure
#print axioms ASGA.hockeyStick_finMeasure
#print axioms ASGA.posPart_sum_le_upperProfile
#print axioms ASGA.monotone_lowerFactor
#print axioms ASGA.lowerProfile_le_posPart_sum
#print axioms ASGA.lowerProfile_le_posPart_sum_log
#print axioms ASGA.lossMass_nonneg
#print axioms ASGA.conv_nonneg
#print axioms ASGA.conv_lossMass
#print axioms ASGA.conv_lossMass_eq_prod
#print axioms ASGA.conv_le_lossMass_prod
#print axioms ASGA.prodMass_nonneg
#print axioms ASGA.lossMass_prod_zero
#print axioms ASGA.lossMass_prod_one
#print axioms ASGA.lossMass_prod_add
#print axioms ASGA.lossMass_prod_succ
#print axioms ASGA.isLowerSub_prod_zero
#print axioms ASGA.isLowerSub_prod_one
#print axioms ASGA.isLowerSub_prod_add
#print axioms ASGA.isLowerSub_prod_iterate
#print axioms ASGA.sum_prodMass
#print axioms ASGA.posPart_sum_prod_le_upperProfile
#print axioms ASGA.lowerProfile_prod_le_posPart_sum
#print axioms ASGA.discreteMeasure_singleton
#print axioms ASGA.pi_discreteMeasure
#print axioms ASGA.hockeyStick_le_upperProfile
#print axioms ASGA.hockeyStick_pi_le_upperProfile
#print axioms ASGA.lowerProfile_le_hockeyStick_pi
#print axioms ASGA.natConv_le_mul_sum
#print axioms ASGA.natConv_le_pow_56
#print axioms ASGA.natConv_le_pow_72
#print axioms ASGA.packNat_mul
#print axioms ASGA.sum_natConv
#print axioms ASGA.digit_sum_pow
#print axioms ASGA.packNat_mul_digit
#print axioms ASGA.pack128_digit
#print axioms ASGA.pack192_digit
#print axioms ASGA.floor_shift_le
#print axioms ASGA.decimal_claims

#print axioms ASGA.callF_eq_callLaw
#print axioms ASGA.putJ_eq_putLaw
